import { CollabInterface } from "./collab.model";

export interface DecComptabiliteInterface {
    _id: string;
    userId: string;
    nature: string;
    mois: string;
    matriculefiscale: string;
    firstname: string;
    lastname: string;
    raisonsociale: null;
    adresse: string;
    codepostal: string;
    activite: string;
    regimefiscalimpot: string;
    sousactivite: string;
    annee: string;
    statutadmin: any[];
    statutcollab: CollabInterface[];
    statutparam: any[];
    totalht: string;
    totaltva: string;
    totaldt: string;
    totalttc: string;
    totalht2: string;
    totaltva2: string;
    totaldt2: string;
    totalttc2: string;
    totalrecette: string;
    totalht3: string;
    totaltva3: string;
    totaldt3: string;
    totalttc3: string;
    totaldebit: string;
    totalcredit: string;
    totalsoldemois: string;
    totalsalairebrut: string;
    totalcnss: string;
    totalsalaireimposable: string;
    totalretenueimpot: string;
    totalavancepret: string;
    totalsalairenet: string;
    totalht219: string;
    totaltva219: string;
    totaldt219: string;
    totalttc219: string;
    totalrecette19: string;
    totalht19: string;
    totaltva19: string;
    totaldt19: string;
    totalttc19: string;
    totalhtexo: string;
    totaltvaexo: string;
    totalhtsus: string;
    totaltvasus: string;
    totalhtexp: string;
    totaltvaexp: string;
    totalttcexo: string;
    totalttcsus: string;
    totalttcexp: string;
    totalht2exo: string;
    totaltva2exo: string;
    totalht2sus: string;
    totaltva2sus: string;
    totalht2exp: string;
    totaltva2exp: string;
    totalttc2exo: string;
    totalttc2sus: string;
    totalttc2exp: string;
    totalrecetteexo: string;
    totalrecettesus: string;
    totalrecetteexp: string;
    source: string;
    contientnumeroother: boolean;
    showbuttonotheretatrecette: boolean;
    contientnumero: boolean;
    autre0: AutreInterface[];
    autre1: AutreInterface[];
    autre2: AutreInterface[];
    autre3: AutreInterface[];
    autre4: AutreInterface[];
    autre5: AutreInterface[];
    autre6: AutreInterface[];
    autre1bis: AutreInterface[];
    autre2bis: AutreInterface[];
    autre3bis: AutreInterface[];
    autre4bis: AutreInterface[];
    autre5bis: AutreInterface[];
    autre6bis: AutreInterface[];
    affecte: string;
    autre11: AutreInterface[];
    autre11bis: AutreInterface[];
    autre8: AutreInterface[];
    autre8bis: AutreInterface[];
    autre9: AutreInterface[];
    autre9bis: AutreInterface[];
    dateouverturedossier: Date;
}

export interface AutreInterface {
    type: string;
    numeropiece: string | number;
    jour: string;
    date: string;
    typepiece: string;
    devise: string;
    montanthtexpdevise: string | number;
    numeronote: string;
    montantht: string;
    montantht19: string;
    montanthtexo: string;
    montanthtsus: string;
    montanthtexp: string | number;
    montanttva: string | number;
    montanttva19: string | number;
    montanttvaexo: string | number;
    montanttvasus: string | number;
    montanttvaexp: string | number | null;
    montantdt: string | number | null;
    montantttc: string | number;
    montantttc19: string | number;
    montantttcexo: string | number;
    montantttcsus: string | number;
    montantttcexp: string | number | null;
    client: string;
    autreclient: string;
    objet: string;
    autreobjet: string;
    annule: string | boolean;
    nature: string;
    autrenature: string;
    banque: string;
    autrebanque: string;
    numerocompte: string;
    autrenumerocompte: string;
    echeance: string;
    datevirement: string;
}