export interface User {
    _id: string;
    email: string;
    password: string;
    confirmpassword: string;
    firstname: string;
    lastname: string;
    fonction: string;
    secteur: string;
    civilite: string;
    usertype: string;
    mobile: string;
    raisonsociale: string;
    nomsociete: string;
    clientcode: string;
    role: string;
    accessToken: string;
    verified: Date;
    matriculefiscale: string;
    natureactivite: string;
    regimefiscalimpot: string;
    regimefiscaltva: string;
    sousactivite: string;
    activite: string;
    adresseactivite: string;
    codepostal: string;
    desactive: {
        date: Date;
        statut: boolean;
    };
    droitcompta: string;
    rolesuperviseur: string;
    connected: boolean;
    choixfacture: any[];
    numeronote: any[];
    paramcomptable: any[];
    coproprietaires: any[];
    choixsyndic: any[];
}